version: 2

project_name: tardis

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-amd64
    binary: tardis
    main: ./cmd/tardis/main.go
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    ldflags:
      - -s -w -X main.Version={{.Version}}

  - id: linux-arm64
    binary: tardis
    main: ./cmd/tardis/main.go
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    ldflags:
      - -s -w -X main.Version={{.Version}}

  - id: darwin-arm64
    binary: tardis
    main: ./cmd/tardis/main.go
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - id: tardis-archive
    builds:
      - linux-amd64
      - linux-arm64
      - darwin-arm64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    files:
      - README.md
      - tardis.example.yml

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
